import { Montserrat, Inter } from "next/font/google";
import "./globals.css";
import "../styles/moon.css";
import "../styles/carousel.css";
import Image from "next/image";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import localFont from "next/font/local";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
})

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
})

const lemonMilk = localFont({
  src: [
    {
      path: "../../public/fonts/lemonmilk-webfont/LemonMilk.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/lemonmilk-webfont/LemonMilkbold.woff",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/fonts/lemonmilk-webfont/LemonMilklight.woff",
      weight: "300",
      style: "normal",
    },
  ],
  variable: "--font-lemon",
})

const modesticSans = localFont({
  src: [
    {
      path: "../../public/fonts/modestic-sans-cdnfonts/ModesticSans-Bold-BF64a47d1515b1b.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/fonts/modestic-sans-cdnfonts/ModesticSans-BoldItalic-BF64a47d15590b5.otf",
      weight: "700",
      style: "italic",
    },
  ],
  variable: "--font-modestic",
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${lemonMilk.variable} ${modesticSans.variable} ${montserrat.variable} ${inter.variable} antialiased`}
      >
        <Header />

        <div className="px-17.5 font-lemon tracking-[2%]">
          {children}
        </div>
        
        {/* BG image */}
        <div className="fixed inset-0 -z-10">
          <Image
            className="object-cover"
            src="/images/pexels-kai-pilger-1341279.png"
            alt="background-image"
            fill
            priority
            // sizes="100vw"  
          />
        </div>

        <Footer />
      </body>
    </html>
  )
}
